In [200]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import re

In [129]:
dataset = pd.read_csv('Consumo_cerveja.csv')

In [131]:
dataset = dataset.rename(columns = {'Data':'Date', 'Temperatura Media (C)': 'Medium Temp', 'Temperatura Minima (C)': 'Minimum Temp',
                           'Temperatura Maxima (C)' : 'Maximum Temp', 'Precipitacao (mm)': 'Precipitation (mm)', 
                          'Final de Semana' : 'End of Week', 'Consumo de cerveja (litros)' : 'Beer Consumption (ltrs)'})

In [198]:
dataset.head()

Date  Medium Temp Minimum Temp Maximum Temp Precipitation (mm)  \
0  01/01/2015        27.30         23,9         32,5                  0   
1  02/01/2015        27.02         24,5         33,5                  0   
2  03/01/2015        24.82         22,4         29,9                  0   
3  04/01/2015        23.98         21,5         28,6                1,2   
4  05/01/2015        23.82           21         28,3                  0   

   End of Week  Beer Consumption (ltrs)  
0            0                   25.461  
1            0                   28.972  
2            1                   30.814  
3            1                   29.799  
4            0                   28.900

In [201]:
dataset['Medium Temp'] = dataset['Medium Temp'].apply(lambda x: np.float(re.sub(r',', '.', x)))

TypeError: expected string or bytes-like object

In [188]:
X = dataset.iloc[:, 1:-1].values

In [189]:
y = dataset.iloc[:, -1].values

In [137]:
df.head()

Medium Temp Minimum Temp Maximum Temp Precipitation (mm)  End of Week  \
0        27,3         23,9         32,5                  0            0   
1       27,02         24,5         33,5                  0            0   
2       24,82         22,4         29,9                  0            1   
3       23,98         21,5         28,6                1,2            1   
4       23,82           21         28,3                  0            0   

   Beer Consumption (ltrs)  
0                   25.461  
1                   28.972  
2                   30.814  
3                   29.799  
4                   28.900

In [197]:
X['Medium Temp'] = X['Medium Temp'].apply(lambda x: np.float(re.sub(r',', '.', x)))

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [191]:
df['Minimum Temp'] = df['Minimum Temp'].replace(',', '.').astype('float')

ValueError: could not convert string to float: '23,9'

In [161]:
df['Maximum Temp'] = df['Maximum Temp'].str.replace(',', '.').astype('float')

In [164]:
df['Precipitation (mm)'] = df['Precipitation (mm)'].replace(',', '.').astype('float')

In [182]:
print(df)

[[27.3   23.9   32.5    0.     0.    25.461]
 [27.02  24.5   33.5    0.     0.    28.972]
 [24.82  22.4   29.9    0.     1.    30.814]
 ...
 [21.68  20.3   24.1   10.3    0.    22.309]
 [21.38  19.3   22.4    6.3    0.    20.467]
 [24.76  20.2   29.     0.     0.    22.446]]


In [183]:

y = df.iloc[:, -1].values

AttributeError: 'numpy.ndarray' object has no attribute 'iloc'

In [180]:
from sklearn.preprocessing import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X)

In [181]:
print(df)

[[27.3   23.9   32.5    0.     0.    25.461]
 [27.02  24.5   33.5    0.     0.    28.972]
 [24.82  22.4   29.9    0.     1.    30.814]
 ...
 [21.68  20.3   24.1   10.3    0.    22.309]
 [21.38  19.3   22.4    6.3    0.    20.467]
 [24.76  20.2   29.     0.     0.    22.446]]
